// ─────────────────────────────────────────────────────────────────────────────
// withReleaseSigning — signs release builds with the KHL upload key.
//
// android/ is regenerated by `expo prebuild`, which resets release signing to
// the debug keystore. This plugin re-applies real signing on every prebuild.
//
// Credentials never live in the repo. They are read at build time from
//   %KHL_SIGNING_PROPS%  or  <user home>/khl-signing/khl-upload.properties
// containing KHL_UPLOAD_STORE_FILE, KHL_UPLOAD_KEY_ALIAS,
// KHL_UPLOAD_STORE_PASSWORD and KHL_UPLOAD_KEY_PASSWORD.
//
// Release builds fail loudly if that file is missing rather than silently
// falling back to the debug key.
// ─────────────────────────────────────────────────────────────────────────────
const { withAppBuildGradle } = require("expo/config-plugins");

const MARKER = "// @khl-release-signing";

const LOADER = `${MARKER}
def khlSigningFile = new File(System.getenv("KHL_SIGNING_PROPS") ?: "\${System.getProperty("user.home")}/khl-signing/khl-upload.properties")
def khlSigning = new Properties()
if (khlSigningFile.exists()) {
    khlSigningFile.withInputStream { khlSigning.load(it) }
}

gradle.taskGraph.whenReady { graph ->
    def buildsRelease = graph.allTasks.any { it.project == project && it.name.contains("Release") }
    if (buildsRelease && !khlSigningFile.exists()) {
        throw new GradleException("Release signing file not found: \${khlSigningFile}. " +
            "Create it (see plugins/withReleaseSigning.js) or set KHL_SIGNING_PROPS.")
    }
}

`;

const RELEASE_CONFIG = `
        release {
            if (khlSigningFile.exists()) {
                storeFile file(khlSigning["KHL_UPLOAD_STORE_FILE"])
                storePassword khlSigning["KHL_UPLOAD_STORE_PASSWORD"]
                keyAlias khlSigning["KHL_UPLOAD_KEY_ALIAS"]
                keyPassword khlSigning["KHL_UPLOAD_KEY_PASSWORD"]
            }
        }`;

function applySigning(gradle) {
  if (gradle.includes(MARKER)) return gradle;

  const fail = (what) => {
    throw new Error(`withReleaseSigning: could not find ${what} in app/build.gradle`);
  };

  // 1. Load the properties file before the android block.
  if (!/^android \{/m.test(gradle)) fail("`android {`");
  gradle = gradle.replace(/^android \{/m, `${LOADER}android {`);

  // 2. Add a release signing config after the debug one.
  const debugConfig = /(signingConfigs \{\s*debug \{[^}]*\})/;
  if (!debugConfig.test(gradle)) fail("signingConfigs.debug");
  gradle = gradle.replace(debugConfig, `$1${RELEASE_CONFIG}`);

  // 3. Point the release build type at it.
  const releaseType = /(buildTypes \{[\s\S]*?release \{[\s\S]*?)signingConfig signingConfigs\.debug/;
  if (!releaseType.test(gradle)) fail("the release buildType's signingConfig");
  gradle = gradle.replace(releaseType, "$1signingConfig signingConfigs.release");

  return gradle;
}

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== "groovy") {
      throw new Error("withReleaseSigning: expected a Groovy app/build.gradle");
    }
    cfg.modResults.contents = applySigning(cfg.modResults.contents);
    return cfg;
  });
};

module.exports.applySigning = applySigning;
